// Issue type list
export const FETCH_ISSUE_TYPES = "FETCH_ISSUE_TYPES";
export const FETCH_ISSUE_TYPES_SUCCESS = "FEATCH_ISSUE_TYPE";
export const FETCH_ISSUE_TYPES_FAILURE = "FEATCH_ISSUE_TYPE";
export const RESET_ISSUE_TYPES = "RESET_ISSUE_TYPE";

// Issue type update
export const UPDATE_ISSUE_TYPE_MODAL = "UPDATE_ISSUE_TYPE_MODAL";
export const UPDATE_ISSUE_TYPE = "UPDATE_ISSUE_TYPE";
export const UPDATE_ISSUE_TYPE_SUCCESS = "UPDATE_ISSUE_TYPE_SUCCESS";
export const UPDATE_ISSUE_TYPE_FAILURE = "UPDATE_ISSUE_TYPE_FAILURE";
export const RESET_UPDATE_ISSUE_TYPE = "RESET_UPDATE_ISSUE_TYPE";

// Fetch Issue type
export const FETCH_ISSUE_TYPE = "FETCH_ISSUE_TYPE";
export const FETCH_ISSUE_TYPE_SUCCESS = "FETCH_ISSUE_TYPE_SUCCESS";
export const FETCH_ISSUE_TYPE_FAILURE = "FETCH_ISSUE_TYPE_FAILURE";
export const RESET_ISSUE_TYPE_FAILURE = "FETCH_ISSUE_TYPE";
// Issue type delete

export const DELETE_ISSUE_TYPE = "DELETE_ISSUE_TYPE";
export const DELETE_ISSUE_TYPE_SUCCESS = "DELETE_ISSUE_TYPE_SUCCESS";
export const DELETE_ISSUE_TYPE_FAILURE = "DELETE_ISSUE_TYPE_FAILURE";
export const RESET_DELETE_ISSUE_TYPE = "RESET_DELETE_ISSUE_TYPE";
