// Issue Status list
export const FETCH_ISSUE_STATUSES = "FETCH_ISSUE_STATUSES";
export const FETCH_ISSUE_STATUSES_SUCCESS = "FETCH_ISSUE_STATUSES_SUCCESS";
export const FETCH_ISSUE_STATUSES_FAILURE = "FETCH_ISSUE_STATUSES_FAILURE";
export const RESET_ISSUE_STATUSES = "RESET_ISSUE_STATUSES";

// Issue Status update
export const UPDATE_ISSUE_STATUS_MODAL = "UPDATE_ISSUE_STATUS_MODAL";
export const UPDATE_ISSUE_STATUS = "UPDATE_ISSUE_STATUS";
export const UPDATE_ISSUE_STATUS_SUCCESS = "UPDATE_ISSUE_STATUS_SUCCESS";
export const UPDATE_ISSUE_STATUS_FAILURE = "UPDATE_ISSUE_STATUS_FAILURE";
export const RESET_UPDATE_ISSUE_STATUS = "RESET_UPDATE_ISSUE_STATUS";

// Fetch Issue Status
export const FETCH_ISSUE_STATUS = "FETCH_ISSUE_STATUS";
export const FETCH_ISSUE_STATUS_SUCCESS = "FETCH_ISSUE_STATUS_SUCCESS";
export const FETCH_ISSUE_STATUS_FAILURE = "FETCH_ISSUE_STATUS_FAILURE";
export const RESET_ISSUE_STATUS_FAILURE = "FETCH_ISSUE_STATUS";
// Issue Status delete

export const DELETE_ISSUE_STATUS = "DELETE_ISSUE_STATUS";
export const DELETE_ISSUE_STATUS_SUCCESS = "DELETE_ISSUE_STATUS_SUCCESS";
export const DELETE_ISSUE_STATUS_FAILURE = "DELETE_ISSUE_STATUS_FAILURE";
export const RESET_DELETE_ISSUE_STATUS = "RESET_DELETE_ISSUE_STATUS";
