// Issue type list
export const FETCH_PRIORITIES = "FETCH_PRIORITIES";
export const FETCH_PRIORITIES_SUCCESS = "FEATCH_PRIORITIES";
export const FETCH_PRIORITIES_FAILURE = "FEATCH_PRIORITIES";
export const RESET_PRIORITIES = "RESET_PRIORITIES";

// Issue type update
export const UPDATE_PRIORITY_MODAL = "UPDATE_PRIORITY_MODAL";
export const UPDATE_PRIORITY = "UPDATE_PRIORITY";
export const UPDATE_PRIORITY_SUCCESS = "UPDATE_PRIORITY_SUCCESS";
export const UPDATE_PRIORITY_FAILURE = "UPDATE_PRIORITY_FAILURE";
export const RESET_UPDATE_PRIORITY = "RESET_UPDATE_PRIORITY";

// Fetch Issue type
export const FETCH_PRIORITY = "FETCH_PRIORITY";
export const FETCH_PRIORITY_SUCCESS = "FETCH_PRIORITY_SUCCESS";
export const FETCH_PRIORITY_FAILURE = "FETCH_PRIORITY_FAILURE";
export const RESET_PRIORITY_FAILURE = "FETCH_PRIORITY";
// Issue type delete

export const DELETE_PRIORITY = "DELETE_PRIORITY";
export const DELETE_PRIORITY_SUCCESS = "DELETE_PRIORITY_SUCCESS";
export const DELETE_PRIORITY_FAILURE = "DELETE_PRIORITY_FAILURE";
export const RESET_DELETE_PRIORITY = "RESET_DELETE_PRIORITY";
