<?php

$tables = array(
    'issue' =>
    array(
        'model_class_name' => 'AutoIssue',
        'peer_class_name' => 'AutoIssuePeer',
        'model_file_name' => 'class.autoissue.php',
        'peer_file_name' => 'class.autoissuepeer.php',
        'table_name' => 'issue',
        'table_columns' => array('id', 'code', 'name', 'description', 'project_id', 'type_id', 'status_id', 'assignee_id', 'creator_id', 'priority', 'parent_issue_id', 'child_ids', 'order_id', 'level', 'start_date', 'end_date', 'complete_percent', 'attachment', 'created_at', 'modified', 'watchers', 'hours'),
        'primary_key' => array('id'),
        'unique_key' => array(),
        'retrieveby_columns' => array(),
        'retrieve_all' => true,
        'generate_edit' => false,
        'generate_list' => false,
        'generate_action' => false,
        'generate_module' => false,
        'view_path' => 'modules/issue/view/auto/',
        'action_path' => 'modules/issue/controller/auto/',
        'view_obj' => 'issue',
        'list_objs' => 'issues', //list tra ve cua function retriveall
        'list_obj' => 'issue',
        'module' => 'issue'//ten module
    ),
    'issuebackup' =>
    array(
        'model_class_name' => 'AutoIssueBackup',
        'peer_class_name' => 'AutoIssueBackupPeer',
        'model_file_name' => 'class.autoissuebackup.php',
        'peer_file_name' => 'class.autoissuebackuppeer.php',
        'table_name' => 'issue_backup',
        'table_columns' => array('id', 'issue_id', 'code', 'name', 'description', 'project_id', 'type_id', 'status_id', 'assignee_id', 'creator_id', 'priority', 'parent_issue_id', 'start_date', 'end_date', 'complete_percent', 'attachment', 'created_at', 'modified', 'comment', 'modifier', 'watchers', 'hours'),
        'primary_key' => array('id'),
        'unique_key' => array(),
        'retrieveby_columns' => array(),
        'retrieve_all' => true,
        'generate_edit' => false,
        'generate_list' => false,
        'generate_action' => false,
        'generate_module' => false,
        'view_path' => 'modules/issuebackup/view/auto/',
        'action_path' => 'modules/issuebackup/controller/auto/',
        'view_obj' => 'issuebackup',
        'list_objs' => 'issuebackups', //list tra ve cua function retriveall
        'list_obj' => 'issuebackup',
        'module' => 'issuebackup'//ten module
    ),
    'project' =>
    array(
        'model_class_name' => 'AutoProject',
        'peer_class_name' => 'AutoProjectPeer',
        'model_file_name' => 'class.autoproject.php',
        'peer_file_name' => 'class.autoprojectpeer.php',
        'table_name' => 'project',
        'table_columns' => array('id', 'name', 'description', 'start_date', 'end_date', 'complete_percent', 'project_status_id', 'created_at', 'creator_id', 'modified'),
        'primary_key' => array('id'),
        'unique_key' => array(),
        'retrieveby_columns' => array(),
        'retrieve_all' => true,
        'generate_edit' => false,
        'generate_list' => false,
        'generate_action' => true,
        'generate_module' => true,
        'view_path' => 'modules/project/view/auto/',
        'action_path' => 'modules/project/controller/auto/',
        'view_obj' => 'project',
        'list_objs' => 'projects', //list tra ve cua function retriveall
        'list_obj' => 'project',
        'module' => 'project'//ten module
    ),
    'userrole' =>
    array(
        'model_class_name' => 'AutoUserRole',
        'peer_class_name' => 'AutoUserRolePeer',
        'model_file_name' => 'class.autouserrole.php',
        'peer_file_name' => 'class.autouserrolepeer.php',
        'table_name' => 'user_role',
        'table_columns' => array('id', 'project_id', 'user_id', 'role_id', 'is_project_default', 'page', 'rows', 'closed_hide', 'orderby', 'sort'),
        'primary_key' => array('id'),
        'unique_key' => array(),
        'retrieveby_columns' => array(),
        'retrieve_all' => true,
        'generate_edit' => false,
        'generate_list' => false,
        'generate_action' => true,
        'generate_module' => true,
        'view_path' => 'modules/userrole/view/auto/',
        'action_path' => 'modules/userrole/controller/auto/',
        'view_obj' => 'userrole',
        'list_objs' => 'userroles', //list tra ve cua function retriveall
        'list_obj' => 'userrole',
        'module' => 'userrole'//ten module
    ),
    'projectstatus' =>
    array(
        'model_class_name' => 'AutoProjectstatus',
        'peer_class_name' => 'AutoProjectstatusPeer',
        'model_file_name' => 'class.autoprojectstatus.php',
        'peer_file_name' => 'class.autoprojectstatuspeer.php',
        'table_name' => 'project_status',
        'table_columns' => array('id', 'name', 'description'),
        'primary_key' => array('id'),
        'unique_key' => array(),
        'retrieveby_columns' => array(),
        'retrieve_all' => true,
        'generate_edit' => false,
        'generate_list' => false,
        'generate_action' => true,
        'generate_module' => true,
        'view_path' => 'modules/projectstatus/view/auto/',
        'action_path' => 'modules/projectstatus/controller/auto/',
        'view_obj' => 'projectstatus',
        'list_objs' => 'projectstatuses', //list tra ve cua function retriveall
        'list_obj' => 'projectstatus',
        'module' => 'projectstatus'//ten module
    ),
    'issuetime' =>
    array(
        'model_class_name' => 'AutoIssueTime',
        'peer_class_name' => 'AutoIssueTimePeer',
        'model_file_name' => 'class.autoissuetime.php',
        'peer_file_name' => 'class.autoissuetimepeer.php',
        'table_name' => 'issue_time',
        'table_columns' => array('id', 'issue_id', 'date', 'hours', 'description'),
        'primary_key' => array('id'),
        'unique_key' => array(),
        'retrieveby_columns' => array(),
        'retrieve_all' => true,
        'generate_edit' => false,
        'generate_list' => false,
        'generate_action' => true,
        'generate_module' => true,
        'view_path' => 'modules/issuetime/view/auto/',
        'action_path' => 'modules/issuetime/controller/auto/',
        'view_obj' => 'issuetime',
        'list_objs' => 'issuetimes', //list tra ve cua function retriveall
        'list_obj' => 'issuetime',
        'module' => 'issuetime'//ten module
    ),
    'issuehistory' =>
    array(
        'model_class_name' => 'AutoIssueHistory',
        'peer_class_name' => 'AutoIssueHistoryPeer',
        'model_file_name' => 'class.autoissuehistory.php',
        'peer_file_name' => 'class.autoissuehistorypeer.php',
        'table_name' => 'issue_history',
        'table_columns' => array('id', 'issue_id', 'assigner_from_id', 'assigner_to_id', 'status_from_id', 'status_to_id', 'created_at'),
        'primary_key' => array('id'),
        'unique_key' => array(),
        'retrieveby_columns' => array(),
        'retrieve_all' => true,
        'generate_edit' => false,
        'generate_list' => false,
        'generate_action' => false,
        'generate_module' => false,
        'view_path' => 'modules/issuehistory/view/auto/',
        'action_path' => 'modules/issuehistory/controller/auto/',
        'view_obj' => 'issuehistory',
        'list_objs' => 'issuehistories',
        'list_obj' => 'issuehistory',
        'module' => 'issuehistory'
    ),
    'issuestatus' =>
    array(
        'model_class_name' => 'AutoIssueStatus',
        'peer_class_name' => 'AutoIssueStatusPeer',
        'model_file_name' => 'class.autoissuestatus.php',
        'peer_file_name' => 'class.autoissuestatuspeer.php',
        'table_name' => 'issue_status',
        'table_columns' => array('id', 'name', 'description', 'color', 'order_id'),
        'primary_key' => array('id'),
        'unique_key' => array(),
        'retrieveby_columns' => array(),
        'retrieve_all' => true,
        'generate_edit' => false,
        'generate_list' => false,
        'generate_action' => true,
        'generate_module' => true,
        'view_path' => 'modules/issuestatus/view/auto/',
        'action_path' => 'modules/issuestatus/controller/auto/',
        'view_obj' => 'issuestatus',
        'list_objs' => 'issuestatuses',
        'list_obj' => 'issuestatus',
        'module' => 'issuestatus'
    ),
    'issuetype' =>
    array(
        'model_class_name' => 'AutoIssueType',
        'peer_class_name' => 'AutoIssueTypePeer',
        'model_file_name' => 'class.autoissuetype.php',
        'peer_file_name' => 'class.autoissuetypepeer.php',
        'table_name' => 'issue_type',
        'table_columns' => array('id', 'name', 'description', 'color'),
        'primary_key' => array('id'),
        'unique_key' => array(),
        'retrieveby_columns' => array(),
        'retrieve_all' => true,
        'generate_edit' => false,
        'generate_list' => false,
        'generate_action' => true,
        'generate_module' => true,
        'view_path' => 'modules/issuetype/view/auto/',
        'action_path' => 'modules/issuetype/controller/auto/',
        'view_obj' => 'issuetype',
        'list_objs' => 'issuetypes',
        'list_obj' => 'issuetype',
        'module' => 'issuetype'
    ),
    'role' =>
    array(
        'model_class_name' => 'AutoRole',
        'peer_class_name' => 'AutoRolePeer',
        'model_file_name' => 'class.autorole.php',
        'peer_file_name' => 'class.autorolepeer.php',
        'table_name' => 'role',
        'table_columns' => array('id', 'name'),
        'primary_key' => array('id'),
        'unique_key' => array('name'),
        'retrieveby_columns' => array(),
        'retrieve_all' => true,
        'generate_edit' => false,
        'generate_list' => false,
        'generate_action' => true,
        'generate_module' => true,
        'view_path' => 'modules/role/view/auto/',
        'action_path' => 'modules/role/controller/auto/',
        'view_obj' => 'role',
        'list_objs' => 'roles',
        'list_obj' => 'role',
        'module' => 'role'
    ),
    'functions' =>
    array(
        'model_class_name' => 'AutoFunctions',
        'peer_class_name' => 'AutoFunctionsPeer',
        'model_file_name' => 'class.autofunctions.php',
        'peer_file_name' => 'class.autofunctionspeer.php',
        'table_name' => 'functions',
        'table_columns' => array('id', 'name', 'description', 'category'),
        'primary_key' => array('id'),
        'unique_key' => array(),
        'retrieveby_columns' => array(),
        'retrieve_all' => true,
        'generate_edit' => false,
        'generate_list' => false,
        'generate_action' => true,
        'generate_module' => true,
        'view_path' => 'modules/functions/view/auto/',
        'action_path' => 'modules/functions/controller/auto/',
        'view_obj' => 'functions',
        'list_objs' => 'functionss',
        'list_obj' => 'functions',
        'module' => 'functions'
    ),
    'user' =>
    array(
        'model_class_name' => 'AutoUser',
        'peer_class_name' => 'AutoUserPeer',
        'model_file_name' => 'class.autouser.php',
        'peer_file_name' => 'class.autouserpeer.php',
        'table_name' => 'user',
        'table_columns' => array('id', 'email_address', 'password', 'full_name', 'is_active', 'token', 'created_at', 'is_admin', 'modified'),
        'primary_key' => array('id'),
        'unique_key' => array(),
        'retrieveby_columns' => array(),
        'retrieve_all' => true,
        'generate_edit' => false,
        'generate_list' => false,
        'generate_action' => true,
        'generate_module' => true,
        'view_path' => 'modules/user/view/auto/',
        'action_path' => 'modules/user/controller/auto/',
        'view_obj' => 'user',
        'list_objs' => 'users',
        'list_obj' => 'user',
        'module' => 'user'
    ),
    'rolefunction' =>
    array(
        'model_class_name' => 'AutoRoleFunction',
        'peer_class_name' => 'AutoRoleFunctionPeer',
        'model_file_name' => 'class.autorolefunction.php',
        'peer_file_name' => 'class.autorolefunctionpeer.php',
        'table_name' => 'role_function',
        'table_columns' => array('id', 'role_id', 'function_id'),
        'primary_key' => array('id'),
        'unique_key' => array(),
        'retrieveby_columns' => array(),
        'retrieve_all' => true,
        'generate_edit' => false,
        'generate_list' => false,
        'generate_action' => false,
        'generate_module' => false,
        'view_path' => 'modules/rolefunction/view/auto/',
        'action_path' => 'modules/rolefunction/controller/auto/',
        'view_obj' => 'rolefunction',
        'list_objs' => 'rolefunctions',
        'list_obj' => 'rolefunction',
        'module' => 'rolefunction'
    ),
    'notifications' =>
    array(
        'model_class_name' => 'AutoNotifications',
        'peer_class_name' => 'AutoNotificationsPeer',
        'model_file_name' => 'class.autonotifications.php',
        'peer_file_name' => 'class.autonotificationspeer.php',
        'table_name' => 'notifications',
        'table_columns' => array('id', 'email_address', 'is_read', 'subject', 'content', 'project_id', 'issue_id','is_visible'),
        'primary_key' => array('id'),
        'unique_key' => array(),
        'retrieveby_columns' => array(),
        'retrieve_all' => true,
        'generate_edit' => true,
        'generate_list' => true,
        'generate_action' => true,
        'generate_module' => true,
        'view_path' => 'modules/notifications/view/auto/',
        'action_path' => 'modules/notifications/controller/auto/',
        'view_obj' => 'notifications',
        'list_objs' => 'notificationss',
        'list_obj' => 'notifications',
        'module' => 'notifications'
    )
);
?>
